#!/bin/sh
#examples
#f2py -c dsaupd.f -m dsaupd -L/usr/lib/blas/atlas:/usr/lib/lapack/atlas
#-llapack -lblas -larpack


#log 
    #2020.1.1 I remove '_64_gfort' in the module name 

f2py -c -m array_permutation array_permutation4py.f90 --fcompiler=gfortran -lgomp  --f90flags="-openmp" 
#f2py -c -m common_64_gfort common4py.f90  -llapack -lblas  --fcompiler=gfortran
f2py -c -m common common4py.f90  -llapack -lblas  -lgomp --f90flags="-openmp" --fcompiler=gfortran

#f2py -c -m random_64_gfort random4py.f90 --fcompiler=gfortran

#use name random2 instead of random to avoid conflict with system module
f2py -c -m random2 random4py.f90 --fcompiler=gfortran     


